language: java
dist: trusty
jdk: oraclejdk8
addons:
  sonarcloud:
    organization: "d3f8a5336ce9588e797e9a71f16a14997b5949856daf7e11f94a1ff158"
    token:
      secure: "7fcafbb9c08010ab87856d4164a690f9fda75df1"
    branches:
      - master
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - git fetch --unshallow
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=InfrastructureSC
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"